[2025-08-17 19:44:09] Tentativa 1 de 5 falhou ao tentar offset nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 19:47:31] Tentativa 1 de 5 falhou ao tentar offset nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 19:47:32] Tentativa 1 de 5 falhou ao tentar offset nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 19:53:11] Tentativa 1 de 5 falhou ao tentar offset nos perfis U com erro: <unknown>.HandleToObject
[2025-08-17 20:04:36] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 20:08:46] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 20:08:53] Erro: (-2147352567, 'Exceção.', (None, None, None, 0, None)) não rastreado - Traceback (most recent call last):
  File "c:\Users\Certheus\OneDrive\Documentos\GitHub\PyCad\main.py", line 183, in <module>
    posicionar_angulos(coord_lcs, angs_in)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Certheus\OneDrive\Documentos\GitHub\PyCad\src\adicionar_informacoes.py", line 98, in posicionar_angulos
    texto.InsertionPoint = ponto_texto
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Certheus\AppData\Local\Programs\Python\Python313\Lib\site-packages\comtypes\client\lazybind.py", line 197, in __setattr__
    self._comobj._invoke(descr.memid, descr.invkind, 0, value)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Certheus\AppData\Local\Programs\Python\Python313\Lib\site-packages\comtypes\automation.py", line 852, in _invoke
    self.__com_Invoke(  # type: ignore
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        memid, riid_null, lcid, invkind, dp, var, None, argerr
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
_ctypes.COMError: (-2147352567, 'Exceção.', (None, None, None, 0, None))

[2025-08-17 20:10:24] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 20:12:28] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 20:12:28] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 21:09:04] Tentativa 1 de 5 falhou ao tentar rotacionar os leitos com erro: Rotate
[2025-08-17 21:09:07] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 21:10:10] Tentativa 1 de 5 falhou ao tentar offset nos perfis U com erro: <unknown>.HandleToObject
[2025-08-17 21:10:58] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 21:11:53] Tentativa 1 de 5 falhou ao tentar dar fillet nos leitos com erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)
[2025-08-17 21:20:02] Inicio da execução ID: H0Dr19w3Dt
[2025-08-17 21:20:08] Erro: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None) não rastreado - Traceback (most recent call last):
  File "c:\Users\Certheus\OneDrive\Documentos\GitHub\PyCad\main.py", line 120, in <module>
    handles_vidros, coord_vidros = offset_vidros(espessura_vidro)
                                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Certheus\OneDrive\Documentos\GitHub\PyCad\src\vidros.py", line 177, in offset_vidros
    if linha.EntityName == 'AcDbLine' and linha.Layer == '0':
                                          ^^^^^^^^^^^
  File "C:\Users\Certheus\AppData\Local\Programs\Python\Python313\Lib\site-packages\win32com\client\dynamic.py", line 620, in __getattr__
    ret = self._oleobj_.Invoke(retEntry.dispid, 0, invoke_type, 1)
pywintypes.com_error: (-2147418111, 'A chamada foi rejeitada pelo chamado.', None, None)

[2025-08-17 21:20:18] Inicio da execução ID: KHC7D5C3vJ
[2025-08-17 21:20:37] Fim da execução ID: KHC7D5C3vJ
